---
kind: pipeline
name: react-ci-cd

steps:
  - name: echo
    image: node:alpine
    commands:
      - echo 'Run CI / CD Pipeline on Drone'
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm test
  - name: prerelease
    image: alpine
    commands:
      - tar -zcvf build.tar.gz build/
    when:
      event: tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github-token
      files:
        - build.tar.gz
    when:
      event: tag
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone-polo
      username: drone-CI