---
kind: pipeline
name: react-ci-cd

steps:
  - name: echo
    image: node:alpine
    commands:
      - echo 'Run CI / CD Pipeline on Drone'
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm test
  # - name: publish
  #   image: plugins/github-release
  #   settings:
  #     api_key: from_secret: github-token
  #     files: *
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone-polo
      username: drone-CI